meta_title: "Notes-Connected - Let's find gigs nearby!"
meta_description: "Find great and varied music events or create your own"
meta_url: "https://www.notes-connected.xyz/"
meta_image: "nc-image.png"
