meta_title: "Notes-Connected - Let's find gigs nearby!"
meta_description: "Find great and varies music events or create your own"
meta_type: "What is this?"
meta_url: "https://www.notes-connected.xyz/"
meta_image: "logo.png"
