module Users
  USERS = [{
    "first_name": "Reese",
    "last_name": "Pechell",
    "email": "rpechell0@dailymail.co.uk",
    "user_name": "rpechell0",
    "password": "uceAQD6M0rlz"
  }, {
    "first_name": "Kissie",
    "last_name": "Androli",
    "email": "kandroli1@java.com",
    "user_name": "kandroli1",
    "password": "lvr5Yivlo"
  }, {
    "first_name": "Yvon",
    "last_name": "Towns",
    "email": "ytowns2@facebook.com",
    "user_name": "ytowns2",
    "password": "z1h8KW9yEmix"
  }, {
    "first_name": "Arlyne",
    "last_name": "Naseby",
    "email": "anaseby3@google.com.hk",
    "user_name": "anaseby3",
    "password": "pF1MC2OuKN"
  }, {
    "first_name": "Justin",
    "last_name": "Viant",
    "email": "jviant4@quantcast.com",
    "user_name": "jviant4",
    "password": "aS7ay8Edc4Rf"
  }, {
    "first_name": "Corby",
    "last_name": "Benettolo",
    "email": "cbenettolo5@cnbc.com",
    "user_name": "cbenettolo5",
    "password": "2E46EGr"
  }, {
    "first_name": "Cello",
    "last_name": "Brandli",
    "email": "cbrandli6@ucla.edu",
    "user_name": "cbrandli6",
    "password": "pSfwCkI7t8U"
  }, {
    "first_name": "Delbert",
    "last_name": "Dobing",
    "email": "ddobing7@phoca.cz",
    "user_name": "ddobing7",
    "password": "v6KShb6n5YAV"
  }, {
    "first_name": "Lurette",
    "last_name": "Tucker",
    "email": "ltucker8@themeforest.net",
    "user_name": "ltucker8",
    "password": "NwDkgDQP5G"
  }, {
    "first_name": "Pearla",
    "last_name": "MacAiline",
    "email": "pmacailine9@cpanel.net",
    "user_name": "pmacailine9",
    "password": "dNg5J7Z7hOm"
  }, {
    "first_name": "Carolan",
    "last_name": "Bramwell",
    "email": "cbramwella@noaa.gov",
    "user_name": "cbramwella",
    "password": "f5g3Tyd"
  }, {
    "first_name": "Giusto",
    "last_name": "Jankovsky",
    "email": "gjankovskyb@oakley.com",
    "user_name": "gjankovskyb",
    "password": "FiKcj5Uirzl9"
  }, {
    "first_name": "Shelden",
    "last_name": "Summers",
    "email": "ssummersc@admin.ch",
    "user_name": "ssummersc",
    "password": "khnqQyqH"
  }, {
    "first_name": "Marjorie",
    "last_name": "Isherwood",
    "email": "misherwoodd@whitehouse.gov",
    "user_name": "misherwoodd",
    "password": "B8BBwK4d4gt"
  }, {
    "first_name": "Lyman",
    "last_name": "Maun",
    "email": "lmaune@printfriendly.com",
    "user_name": "lmaune",
    "password": "hGSa7FP9F0s"
  }, {
    "first_name": "Yelena",
    "last_name": "Moncarr",
    "email": "ymoncarrf@google.pl",
    "user_name": "ymoncarrf",
    "password": "MB2TAOP7jJ7X"
  }, {
    "first_name": "Ava",
    "last_name": "Dubble",
    "email": "adubbleg@narod.ru",
    "user_name": "adubbleg",
    "password": "bJbTucRoO4AH"
  }, {
    "first_name": "Renaldo",
    "last_name": "Mutlow",
    "email": "rmutlowh@aol.com",
    "user_name": "rmutlowh",
    "password": "69KsOjw"
  }, {
    "first_name": "Sharity",
    "last_name": "Cavozzi",
    "email": "scavozzii@msn.com",
    "user_name": "scavozzii",
    "password": "Ae3P5BBDqb"
  }, {
    "first_name": "Jessey",
    "last_name": "Fidler",
    "email": "jfidlerj@netlog.com",
    "user_name": "jfidlerj",
    "password": "UvHJIKWs6lM"
  }, {
    "first_name": "Myrilla",
    "last_name": "Garron",
    "email": "mgarronk@tuttocitta.it",
    "user_name": "mgarronk",
    "password": "91owwo0"
  }, {
    "first_name": "Win",
    "last_name": "Harcarse",
    "email": "wharcarsel@indiegogo.com",
    "user_name": "wharcarsel",
    "password": "M2qfRLt"
  }, {
    "first_name": "Colas",
    "last_name": "Lakeland",
    "email": "clakelandm@stanford.edu",
    "user_name": "clakelandm",
    "password": "3tSlgW"
  }, {
    "first_name": "Caspar",
    "last_name": "Mordie",
    "email": "cmordien@google.de",
    "user_name": "cmordien",
    "password": "rb4svNO"
  }, {
    "first_name": "Haroun",
    "last_name": "Leighton",
    "email": "hleightono@google.it",
    "user_name": "hleightono",
    "password": "EGgaJQS"
  }, {
    "first_name": "Renato",
    "last_name": "Cheves",
    "email": "rchevesp@scribd.com",
    "user_name": "rchevesp",
    "password": "vR6V92Muc1X"
  }, {
    "first_name": "Hetty",
    "last_name": "Lehemann",
    "email": "hlehemannq@wikia.com",
    "user_name": "hlehemannq",
    "password": "n6ypKqpMj"
  }, {
    "first_name": "Bealle",
    "last_name": "Dinley",
    "email": "bdinleyr@msn.com",
    "user_name": "bdinleyr",
    "password": "LsT66G8"
  }, {
    "first_name": "Elenore",
    "last_name": "Blakeborough",
    "email": "eblakeboroughs@lulu.com",
    "user_name": "eblakeboroughs",
    "password": "ffaWXJ"
  }, {
    "first_name": "Devlin",
    "last_name": "Bougen",
    "email": "dbougent@utexas.edu",
    "user_name": "dbougent",
    "password": "arHV2KMF"
  }, {
    "first_name": "Elijah",
    "last_name": "Dear",
    "email": "edearu@unesco.org",
    "user_name": "edearu",
    "password": "ktx8D3Db"
  }, {
    "first_name": "Trever",
    "last_name": "Strond",
    "email": "tstrondv@bloomberg.com",
    "user_name": "tstrondv",
    "password": "9lHCNSjpj"
  }, {
    "first_name": "Drew",
    "last_name": "Tolerton",
    "email": "dtolertonw@mediafire.com",
    "user_name": "dtolertonw",
    "password": "DDcWBUvUWG"
  }, {
    "first_name": "Eldridge",
    "last_name": "Meindl",
    "email": "emeindlx@imageshack.us",
    "user_name": "emeindlx",
    "password": "xkQFeca0dQ8"
  }, {
    "first_name": "Simona",
    "last_name": "Milhench",
    "email": "smilhenchy@theguardian.com",
    "user_name": "smilhenchy",
    "password": "EvjPnH"
  }, {
    "first_name": "Nikki",
    "last_name": "Aggis",
    "email": "naggisz@cmu.edu",
    "user_name": "naggisz",
    "password": "UCv3IxPa"
  }, {
    "first_name": "Bogart",
    "last_name": "Cowope",
    "email": "bcowope10@washington.edu",
    "user_name": "bcowope10",
    "password": "jYCoZXzSx"
  }, {
    "first_name": "Audy",
    "last_name": "Cousins",
    "email": "acousins11@example.com",
    "user_name": "acousins11",
    "password": "ndRy05b7"
  }, {
    "first_name": "Mohammed",
    "last_name": "Jozefczak",
    "email": "mjozefczak12@livejournal.com",
    "user_name": "mjozefczak12",
    "password": "z3wwLugZVBE8"
  }, {
    "first_name": "Claudette",
    "last_name": "Perkis",
    "email": "cperkis13@digg.com",
    "user_name": "cperkis13",
    "password": "swanKpd"
  }, {
    "first_name": "Allans",
    "last_name": "Jacmars",
    "email": "ajacmar14@home.pls",
    "user_name": "ajacmar14s",
    "password": "ajacmar14@home.pls"
  }, {
    "first_name": "Wally",
    "last_name": "Wylie",
    "email": "wwylie15@about.me",
    "user_name": "wwylie15",
    "password": "kdQGQmTxQBX"
  }, {
    "first_name": "Rebbecca",
    "last_name": "Elacoate",
    "email": "relacoate16@elpais.com",
    "user_name": "relacoate16",
    "password": "KNu3plGu"
  }, {
    "first_name": "Claresta",
    "last_name": "Cossom",
    "email": "ccossom17@nps.gov",
    "user_name": "ccossom17",
    "password": "nFxLRoF"
  }, {
    "first_name": "Miriam",
    "last_name": "Giddings",
    "email": "mgiddings18@purevolume.com",
    "user_name": "mgiddings18",
    "password": "i7H2NZjnPN"
  }, {
    "first_name": "Annis",
    "last_name": "Cyseley",
    "email": "acyseley19@vk.com",
    "user_name": "acyseley19",
    "password": "anIdVg"
  }, {
    "first_name": "Shana",
    "last_name": "Challoner",
    "email": "schalloner1a@dell.com",
    "user_name": "schalloner1a",
    "password": "HAfinNxFShB"
  }, {
    "first_name": "Juan",
    "last_name": "Berndtsson",
    "email": "jberndtsson1b@list-manage.com",
    "user_name": "jberndtsson1b",
    "password": "sTElb2s"
  }, {
    "first_name": "Catie",
    "last_name": "Craise",
    "email": "ccraise1c@multiply.com",
    "user_name": "ccraise1c",
    "password": "0SITns0Wdoye"
  }, {
    "first_name": "Beryl",
    "last_name": "Bianco",
    "email": "bbianco1d@wordpress.org",
    "user_name": "bbianco1d",
    "password": "e0DPxQ"
  }, {
    "first_name": "Berna",
    "last_name": "Micklewicz",
    "email": "bmicklewicz1e@blogger.com",
    "user_name": "bmicklewicz1e",
    "password": "HehqvZpdT2"
  }, {
    "first_name": "Fabien",
    "last_name": "Portam",
    "email": "fportam1f@google.co.uk",
    "user_name": "fportam1f",
    "password": "12JGN6zCZ"
  }, {
    "first_name": "Darb",
    "last_name": "Clelland",
    "email": "dclelland1g@economist.com",
    "user_name": "dclelland1g",
    "password": "nXZKE55oCvc"
  }, {
    "first_name": "Patsy",
    "last_name": "Parkman",
    "email": "pparkman1h@google.co.uk",
    "user_name": "pparkman1h",
    "password": "s4EpGu"
  }, {
    "first_name": "Monty",
    "last_name": "Erskin",
    "email": "merskin1i@merriam-webster.com",
    "user_name": "merskin1i",
    "password": "X5iDhiZbb"
  }, {
    "first_name": "Esra",
    "last_name": "Shakespear",
    "email": "eshakespear1j@seattletimes.com",
    "user_name": "eshakespear1j",
    "password": "FKa4n1"
  }, {
    "first_name": "Eyde",
    "last_name": "Munks",
    "email": "emunks1k@accuweather.com",
    "user_name": "emunks1k",
    "password": "lFLj1Z07"
  }, {
    "first_name": "Tiena",
    "last_name": "Sans",
    "email": "tsans1l@time.com",
    "user_name": "tsans1l",
    "password": "aEAmBkchr"
  }, {
    "first_name": "Caril",
    "last_name": "Radnage",
    "email": "cradnage1m@eventbrite.com",
    "user_name": "cradnage1m",
    "password": "zKLSTSgG"
  }, {
    "first_name": "Wyndham",
    "last_name": "Henstone",
    "email": "whenstone1n@bloglines.com",
    "user_name": "whenstone1n",
    "password": "onxPmTDcgv8P"
  }, {
    "first_name": "Hynda",
    "last_name": "Cancellor",
    "email": "hcancellor1o@tamu.edu",
    "user_name": "hcancellor1o",
    "password": "ydWNoqWlz"
  }, {
    "first_name": "Bink",
    "last_name": "Culvey",
    "email": "bculvey1p@scribd.com",
    "user_name": "bculvey1p",
    "password": "tKnefy7HHbP"
  }, {
    "first_name": "Isaiah",
    "last_name": "Ajean",
    "email": "iajean1q@jalbum.net",
    "user_name": "iajean1q",
    "password": "fdVxKtMkqh"
  }, {
    "first_name": "Marchelle",
    "last_name": "Halse",
    "email": "mhalse1r@kickstarter.com",
    "user_name": "mhalse1r",
    "password": "TSHAR0nEcd8d"
  }, {
    "first_name": "Randall",
    "last_name": "Boolsen",
    "email": "rboolsen1s@soup.io",
    "user_name": "rboolsen1s",
    "password": "Vt0Edr4wHvXo"
  }, {
    "first_name": "Matthias",
    "last_name": "Wittleton",
    "email": "mwittleton1t@blogs.com",
    "user_name": "mwittleton1t",
    "password": "vvgoTIgbE2s"
  }, {
    "first_name": "Roland",
    "last_name": "Carillo",
    "email": "rcarillo1u@springer.com",
    "user_name": "rcarillo1u",
    "password": "be7ZpE9i"
  }, {
    "first_name": "Honor",
    "last_name": "Lahiff",
    "email": "hlahiff1v@goo.gl",
    "user_name": "hlahiff1v",
    "password": "Cj2fAWE"
  }, {
    "first_name": "Sayre",
    "last_name": "Lindberg",
    "email": "slindberg1w@github.io",
    "user_name": "slindberg1w",
    "password": "Nx08M00Grfd"
  }, {
    "first_name": "Catina",
    "last_name": "Stayte",
    "email": "cstayte1x@google.ca",
    "user_name": "cstayte1x",
    "password": "THtdvkeQ"
  }, {
    "first_name": "Cordey",
    "last_name": "Dible",
    "email": "cdible1y@goo.gl",
    "user_name": "cdible1y",
    "password": "sgrOI2YIU0us"
  }, {
    "first_name": "Fabian",
    "last_name": "Methley",
    "email": "fmethley1z@columbia.edu",
    "user_name": "fmethley1z",
    "password": "KEF3u3"
  }, {
    "first_name": "Umeko",
    "last_name": "Britian",
    "email": "ubritian20@delicious.com",
    "user_name": "ubritian20",
    "password": "WQpgbSFeG"
  }, {
    "first_name": "Zebulon",
    "last_name": "Craisford",
    "email": "zcraisford21@eventbrite.com",
    "user_name": "zcraisford21",
    "password": "BOSC76"
  }, {
    "first_name": "Eunice",
    "last_name": "Sunley",
    "email": "esunley22@cbslocal.com",
    "user_name": "esunley22",
    "password": "z5cd3mf6S"
  }, {
    "first_name": "Prent",
    "last_name": "Paver",
    "email": "ppaver23@people.com.cn",
    "user_name": "ppaver23",
    "password": "YobLvJt5m"
  }, {
    "first_name": "Mickie",
    "last_name": "Yakunin",
    "email": "myakunin24@sina.com.cn",
    "user_name": "myakunin24",
    "password": "fOb8tJZ"
  }, {
    "first_name": "Homerus",
    "last_name": "Macconaghy",
    "email": "hmacconaghy25@jiathis.com",
    "user_name": "hmacconaghy25",
    "password": "tCJufTbw2"
  }, {
    "first_name": "Bartholomeo",
    "last_name": "Gatenby",
    "email": "bgatenby26@loc.gov",
    "user_name": "bgatenby26",
    "password": "U7E4mQ5M"
  }, {
    "first_name": "Lorianne",
    "last_name": "Simonnin",
    "email": "lsimonnin27@jalbum.net",
    "user_name": "lsimonnin27",
    "password": "QCZNVnELA"
  }, {
    "first_name": "Basilius",
    "last_name": "Stuckford",
    "email": "bstuckford28@wiley.com",
    "user_name": "bstuckford28",
    "password": "gSLlbFUWY"
  }, {
    "first_name": "Joscelin",
    "last_name": "McDonell",
    "email": "jmcdonell29@topsy.com",
    "user_name": "jmcdonell29",
    "password": "5Fij23TYX"
  }, {
    "first_name": "Emilee",
    "last_name": "Bubear",
    "email": "ebubear2a@odnoklassniki.ru",
    "user_name": "ebubear2a",
    "password": "B0EMxRF"
  }, {
    "first_name": "Sophey",
    "last_name": "Bosse",
    "email": "sbosse2b@wikispaces.com",
    "user_name": "sbosse2b",
    "password": "Q9ufS5fW"
  }, {
    "first_name": "Marabel",
    "last_name": "Newbigging",
    "email": "mnewbigging2c@whitehouse.gov",
    "user_name": "mnewbigging2c",
    "password": "pTj3KzKgmQ5J"
  }, {
    "first_name": "Adrien",
    "last_name": "Stogill",
    "email": "astogill2d@twitpic.com",
    "user_name": "astogill2d",
    "password": "hPUNXN4"
  }, {
    "first_name": "Hillary",
    "last_name": "McElory",
    "email": "hmcelory2e@goo.ne.jp",
    "user_name": "hmcelory2e",
    "password": "cJZzsqz6JG"
  }, {
    "first_name": "Melodee",
    "last_name": "Corden",
    "email": "mcorden2f@accuweather.com",
    "user_name": "mcorden2f",
    "password": "1I41vXC2m4z"
  }, {
    "first_name": "Tiebold",
    "last_name": "Coe",
    "email": "tcoe2g@typepad.com",
    "user_name": "tcoe2g",
    "password": "nlUO66xMDRs"
  }, {
    "first_name": "Legra",
    "last_name": "McCritichie",
    "email": "lmccritichie2h@army.mil",
    "user_name": "lmccritichie2h",
    "password": "f8TYzjrh0g1"
  }, {
    "first_name": "Thurstan",
    "last_name": "Anton",
    "email": "tanton2i@apple.com",
    "user_name": "tanton2i",
    "password": "sNWyTx"
  }, {
    "first_name": "Lane",
    "last_name": "Tynan",
    "email": "ltynan2j@cdbaby.com",
    "user_name": "ltynan2j",
    "password": "dHsKyjiRyXx"
  }, {
    "first_name": "Corinna",
    "last_name": "Hanna",
    "email": "channa2k@theatlantic.com",
    "user_name": "channa2k",
    "password": "BnfNnl7QAr8X"
  }, {
    "first_name": "Milo",
    "last_name": "Kreber",
    "email": "mkreber2l@google.co.jp",
    "user_name": "mkreber2l",
    "password": "pOB7yTdC4"
  }, {
    "first_name": "Foss",
    "last_name": "Monday",
    "email": "fmonday2m@nymag.com",
    "user_name": "fmonday2m",
    "password": "sf3aX88"
  }, {
    "first_name": "Berky",
    "last_name": "Hallett",
    "email": "bhallett2n@narod.ru",
    "user_name": "bhallett2n",
    "password": "coVKQwk"
  }, {
    "first_name": "Audi",
    "last_name": "Rossi",
    "email": "arossi2o@jalbum.net",
    "user_name": "arossi2o",
    "password": "mZ5jDA"
  }, {
    "first_name": "William",
    "last_name": "Pamphilon",
    "email": "wpamphilon2p@rediff.com",
    "user_name": "wpamphilon2p",
    "password": "QvS7SzHXRir"
  }, {
    "first_name": "Isacco",
    "last_name": "Docherty",
    "email": "idocherty2q@paginegialle.it",
    "user_name": "idocherty2q",
    "password": "FAY3NBUOlJK"
  }, {
    "first_name": "Culver",
    "last_name": "Jerok",
    "email": "cjerok2r@storify.com",
    "user_name": "cjerok2r",
    "password": "jwd0xC3"
  }]
end
